use std::env;
use std::fmt::Write as _;
use std::fs;
use std::panic;
use std::path::Path;

fn parse_color(s: &str) -> String {
    if s.starts_with('#') {
        if s.len() == 4 {
            "0x".to_string() + &s.trim_start_matches('#').chars().map(|c| format!("{c}{c}")).collect::<String>()
        } else if s.len() == 7 {
            "0x".to_string() + s.trim_start_matches('#')
        } else {
            panic!("Color code must be 3 or 6 hex digits: {s}");
        }
    } else {
        panic!("Color code must start with '#': {s}");
    }
}

#[derive(Default)]
pub struct Palette {
    pub name: String,
    pub author: Option<String>,
    pub url: Option<String>,
    pub style: Option<String>,
    pub foreground: String,
    pub background: String,
    pub cursor: String,
    pub ansi_colors: [String; 16],
}

fn load_palettes() -> Vec<Palette> {
    println!("cargo:rerun-if-changed=src/palettes.md");
    let palettes = fs::read_to_string("src/palettes.md").expect("Failed to read palettes.md");
    let palettes = palettes.lines().filter(|s| !s.trim().is_empty()).collect::<Vec<&str>>();
    let palettes = palettes.into_iter().fold((Vec::new(), Vec::new()), |(mut palettes, mut rem), line| {
        if line.starts_with("## ") && !rem.is_empty() {
            let rem = std::mem::take::<Vec<&str>>(&mut rem);
            if rem[0].starts_with("## ") {
                palettes.push(rem);
            }
        }
        rem.push(line);
        (palettes, rem)
    });
    let palettes = {
        let (mut palettes, rem) = palettes;
        if !rem.is_empty() && rem[0].starts_with("## ") {
            palettes.push(rem);
        }
        palettes
    };

    let palettes = palettes.into_iter().map(|texts| {
        let mut num_min_colors = -1;
        let mut palette = Palette::default();
        for line in texts {
            if let Some(line) = line.strip_prefix("## ") {
                palette.name = line.trim().to_string();
            } else if let Some(line) = line.strip_prefix('>') {
                palette.author = Some(line.trim().to_string());
            } else if line.starts_with('<') && line.ends_with('>') {
                palette.url = Some(line[1..line.len() - 1].trim().to_string());
            } else if line.starts_with('`') && line.ends_with('`') {
                palette.style = Some(line[1..line.len() - 1].trim().to_string());
            } else if let Some(line) = line.strip_prefix("-") {
                let colors =
                    line.split(',').map(str::trim).filter(|s| !s.is_empty()).map(parse_color).collect::<Vec<String>>();
                if num_min_colors < 0 {
                    if colors.len() != 2 && colors.len() != 3 {
                        panic!("Major colors must be exactly 2 or 3 in palette: {}", palette.name);
                    }
                    palette.foreground = colors[0].clone();
                    palette.background = colors[1].clone();
                    if colors.len() == 2 {
                        palette.cursor = colors[0].clone();
                    } else {
                        palette.cursor = colors[2].clone();
                    }
                    num_min_colors = 0;
                } else {
                    for color in colors {
                        if num_min_colors >= 16 {
                            panic!("Too many minor colors in palette: {}", palette.name);
                        }
                        palette.ansi_colors[num_min_colors as usize] = color;
                        num_min_colors += 1;
                    }
                }
            } else {
                panic!("Unrecognized line in palette: {}", palette.name);
            }
        }
        if num_min_colors < 16 {
            panic!("Not enough minor colors in palette: {}", palette.name);
        }
        palette
    });

    palettes.collect()
}

#[rustfmt::skip]
#[allow(unused_must_use)]
fn gen_palettes() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR environment variable not set");
    let dest_path = Path::new(&out_dir).join("palettes.rs");

    let palettes = load_palettes();
    assert!(!palettes.is_empty(), "No palettes found in palettes.md");

    let mut code = String::new();

    writeln!(code, "// This file is auto-generated by build.rs from src/palettes.md.");
    writeln!(code, "// Do not edit this file directly.");
    writeln!(code);
    writeln!(code, "/// 内置的调色板列表");
    writeln!(code, "/// - 调色板来自网络，版权归原作者所有。");
    writeln!(code, "///");
    writeln!(code, "/// The list of built-in color schemes.");
    writeln!(code, "/// - The color schemes are collected from the Internet, and the copyright belongs to the original authors.");
    writeln!(code, "#[rustfmt::skip]");
    writeln!(code, "const PALETTES: [Palette; {}] = [", palettes.len());
    for palette in palettes {
        writeln!(code, "    Palette::new(");
        writeln!(code, "        \"{}\",", palette.name);
        writeln!(code, "        ({}, {}, {}),", palette.foreground, palette.background, palette.cursor);
        writeln!(code, "        [");
        writeln!(code, "            {}, {}, {}, {}, {}, {}, {}, {},", palette.ansi_colors[0], palette.ansi_colors[1], palette.ansi_colors[2], palette.ansi_colors[3], palette.ansi_colors[4], palette.ansi_colors[5], palette.ansi_colors[6], palette.ansi_colors[7]);
        writeln!(code, "            {}, {}, {}, {}, {}, {}, {}, {},", palette.ansi_colors[8], palette.ansi_colors[9], palette.ansi_colors[10], palette.ansi_colors[11], palette.ansi_colors[12], palette.ansi_colors[13], palette.ansi_colors[14], palette.ansi_colors[15]);
        writeln!(code, "        ],");
        writeln!(code, "    ),");
    }
    writeln!(code, "];");
    writeln!(code);
    writeln!(code, "const DEFAULT_PALETTE_INDEX: usize = 0;");

    fs::write(&dest_path, code).unwrap();
}

fn check_features() {
    let features = [
        ("default-rgba", cfg!(feature = "default-rgba")),
        ("default-bgra", cfg!(feature = "default-bgra")),
        ("default-argb", cfg!(feature = "default-argb")),
        ("default-abgr", cfg!(feature = "default-abgr")),
    ];

    let enabled: Vec<&str> =
        features.iter().filter_map(|(name, enabled)| if *enabled { Some(*name) } else { None }).collect();

    let hint = "Please enable exactly one of: default-rgba, default-bgra, default-argb, default-abgr in Cargo.toml.";
    match enabled.len() {
        1 => {}
        0 => panic!("Error: No pixel format feature enabled. {hint}"),
        _ => panic!("Error: Multiple pixel format features enabled ({enabled:?}). {hint}"),
    }

    let woff2 = cfg!(feature = "font-woff2");
    let abglyph = cfg!(feature = "font-abglyph");
    let swash = cfg!(feature = "font-swash");
    if woff2 && !(abglyph || swash) {
        panic!("Error: font-woff2 feature requires a TrueType backend (enable font-abglyph or font-swash).");
    }
}

fn main() {
    check_features();
    gen_palettes();
}
